# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae41de590ed4755f2d7f887bf52e7d85326ec77cd49d57d271e555e701341adeb41ca0ea522f69dfca992a1418cb9d5eddbdd1529f8e6ca925ebee7910653a4b

test:
  secret_key_base: 872491e4a94ba1415e7f896c618b4a0a0c1a7092058b906b2ebf91cc2b60aa63ae56a468c5577a8821d275c185a5e6d5727960f544b2d225adeb7b1aaddd2ee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
